// <auto-generated />
using System;
using EmailSelect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SqlServerMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmailSelect.Models.RuleSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociationId");

                    b.ToTable("RuleSelections");
                });

            modelBuilder.Entity("EmailSelect.Models.SelectedRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleSelectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleSelectionId");

                    b.ToTable("SelectedRule");
                });

            modelBuilder.Entity("EmailSelect.Models.SelectionAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SelectionAssociations");
                });

            modelBuilder.Entity("EmailSelect.Models.RuleSelection", b =>
                {
                    b.HasOne("EmailSelect.Models.SelectionAssociation", "SelectionAssociation")
                        .WithMany("RuleSelections")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelectionAssociation");
                });

            modelBuilder.Entity("EmailSelect.Models.SelectedRule", b =>
                {
                    b.HasOne("EmailSelect.Models.RuleSelection", null)
                        .WithMany("SelectedRules")
                        .HasForeignKey("RuleSelectionId");
                });

            modelBuilder.Entity("EmailSelect.Models.RuleSelection", b =>
                {
                    b.Navigation("SelectedRules");
                });

            modelBuilder.Entity("EmailSelect.Models.SelectionAssociation", b =>
                {
                    b.Navigation("RuleSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
